hasWeightVar: true
weightVar:
  stdDev: 0.1 # the std dev of variation
  sampleTimes: 50 # for each mid-point separation value, sample #sampleTimes values of the value after variation for averaging the information gain
